name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Check Dockerfile with Hadolint
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile

    - name: Build and push Docker image
      run: |
        docker build -t elordiner/weather-api:latest .
        docker push elordiner/weather-api:latest
